
export const strings = {
  en: {
    Welcome: 'Welcome',
    Acces: 'Access',
    Enter:'Enter',
    Dashboard: 'Dashboard',
    Security: 'Security',
    Logout: 'Logout',
    Register: 'Register',
    Login: 'Login',
    Home: 'Home',
    Page: 'Page',
    of: 'of',
    Detail: 'Detail',
    back:'Back',
    Screenshot: 'Screenshot',
    Extra: 'Extra',
    Minimum_requirements: "Minimum Requirements",
    Genres: "Genres",
    Plataformas: "Platforms",
    Capture:'Capture',
    Item_added:'Item Added',
    Shopping_Car: 'Shopping Car',
    Items: 'Items',
    Number: 'Number',
    Checkout : 'Checkout',
    MsgUserNoRegister: 'Unregistered User login to your account',
    Search: 'Search',
    Information: 'Information',
    Ranking: 'Ranking',
    Release: 'Release Date',
    DarkMode: 'Dark Mode',
    Languaje:  'Change Language',
    Landing: 'Landing',
    MyVideogames:'MyVideo Games',
    Communications: 'Communications',
    MyPosts: 'My Posts',
    youtCart: 'Your Cart',
    clCart:'Clear Cart',
    chkOut:'CheckOut',
    emptycar: 'Your cart is empty',
    MsgAlertTitle:'Are you sure you want to clear the cart?' ,
    optCancel: 'Cancel',
    remove:'Remove',
    MsgAlertAmountMax:'Sorry, the maximum number of purchases per title is 3.',
    MsgAlertItemAmountAdd: 'One unit has been added to the current item',
    MSGAlertItemAdd: 'Item has been added',
    addItemCar: 'Add to cart',
    Sign_inWith: 'Sign in with',
    or: 'Or',
    userName:'User Name',
    CartValidate:'Attention, you must log in to proceed with the purchase.',
    GameList:'Game List',
    MyProfile: 'My Profile',
    MyShoppings: 'My Shoppings',
    MyVotes: 'My Votes',
    VideogamesList: 'Videogames List',
    UserList: 'Users List',
    Sales: 'Sales',
    CreateVideogame: 'Create Videogame',
    PublishItem: 'Publish Items',
    Metrics: 'Metrics',
    Pasarella: 'Payment Gateway',
    title: 'Title',
    price: 'Price',
    description: 'Description',
    systemRequeriments: 'System Requeriments',
    releaseDate: 'Release Date',
    videogameCover:'Videogame Cover',
    loadFromGallery:'Load From Gallery',
    loadScreens:'Load Screenshots',
    addGenre:'Add Genre',
    addPlatforms:'Add Platforms',
    addTags:'Add Tags',
    createPublication:'Create Publication',
    cancelPub:'Cancel Publication',
    MyVotes:'My Votes',
    VideoGameList:'Videogames List',
    UserList:'User List',
    allSalesUser:'All Sales User',
    Admin: 'Administrator User',
    create:'Create',
    cancel:'Cancel',
  },
  es: {
    Welcome: 'Bienvenido',
    Acces: 'Acceder',
    Enter:'Ingresar',
    Dashboard: 'Panel de Usuario',
    Security: 'Securidad',
    Logout: 'Cerrar la sesión',
    Register: 'Registrate',
    Login: 'Iniciar Sesión',
    Home: 'Inicio',
    Page: 'Pagina',
    of: 'de',
    Detail: 'Detalle',
    back:'Regresar',
    Screenshot: 'Captura de Pantalla',
    Extra: 'Extra',
    Minimum_requirements: "Requerimientos Minimos ",
    Genres: "Generos",
    Plataformas: "Plataformas",
    Capture:'Captura',
    Item_added:'Artículo añadido',
    Shopping_Car: 'Carrito de Compras',
    Items: 'Articulos',
    Number: 'Número',
    Checkout : 'Pago',
    MsgUserNoRegister: 'Usuario no registrado acceder a su cuenta',
    Search: 'Buscar',
    Information: 'Información',
    Ranking: 'Clasificación',
    Release: 'Fecha de Lanzamiento',
    DarkMode: 'Modo Oscuro',
    Languaje:  'Cambiar Lenguaje',
    Landing: 'Aterrizaje',
    MyVideogames:'Mis Video Juegos',
    Communications: 'Comunicaciones',
    MyPosts: 'Mis Mensajes',
    youtCart: 'Tu cesta',
    clCart:'Borrar cesta',
    chkOut:'Pagar',
    emptycar: 'Tu cesta está vacía',
    MsgAlertTitle:'¿Estás seguro de que quieres vaciar el carrito?' ,
    optCancel: 'Cancelar',
    remove:'Eliminar',
    MsgAlertAmountMax:'Lo Sentimos el numero maximo de compras por titulo es 3.',
    MsgAlertItemAmountAdd: 'Se adiciono una unidad al item actual',
    MSGAlertItemAdd: 'Ítem ha sido agregado',
    addItemCar: 'Añadir a la Cesta',
    Sign_inWith: 'Registrate con',    
    or: 'O',
    userName:'Nombre de Usuario',
    CartValidate:'Atencion, debe iniciar sesión para proceder con compra.',
    GameList:'Lista de Videojuegos',
    MyProfile: 'Mi Perfil',
    MyShoppings: 'Mis Compras',
    MyVotes: 'Mis Votos',
    VideogamesList: 'Lista de Videojuegos',
    UserList: 'Lista de Usuarios',
    Sales: 'Ventas',
    CreateVideogame: 'Crear Videojuego',
    PublishItem: 'Items Publicados',
    Metrics: 'Estadisticas',
    Pasarella: 'Pasarela de Pago',
    GameList:'Lista de Videojuegos',
    title:'Titulo',
    price:'Precio',
    description: 'Descripcion',
    systemRequeriments: 'Requisitos del Sistema',
    releaseDate: 'Fecha de Lanzamiento',
    videogameCover:'Portada del Videojuego',
    loadFromGallery: 'Cargar de la Galeria',
    loadScreens: 'Cargar Capturas de Pantalla',
    addGenre:'Añadir Genero',
    addPlatforms:'Añadir Plataformas',
    addTags:'Añadir Etiquetas',
    createPublication:'Crear Publicacion',
    cancelPub:'Cancelar Publicacion',
    MyVotes:'Mis Votos',
    VideoGameList:'Lista de Videojuegos',
    UserList:'Lista de Usuarios',
    allSalesUser:' Ventas del Usuario',
    Admin: 'Usuario Administrador',
    create:'Crear',
    cancel:'Cancelar',
  }
};



